Repository APPSCHOOL2-Android/FinalProject-ShoppingMallService-team3, pull requests merged in 2023-08, with the labels that each got.

#10 [판매자용] 로그인 및 회원가입 기능구현
  Swimmer_customer/.idea/gradle.xml
  Swimmer_customer/.idea/misc.xml
  Swimmer_seller/.idea/gradle.xml
  Swimmer_seller/.idea/misc.xml
  Swimmer_seller/.idea/vcs.xml
  Swimmer_seller/app/build.gradle
  Swimmer_seller/app/google-services.json
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/MainActivity.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/UserRepository.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Address.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Seller.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/main/MainFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/LoginFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/SignUpFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/SignUpInfoFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/UserResult.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/UserViewModel.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/UserViewModelFactory.kt
  Swimmer_seller/app/src/main/res/drawable/arrow_back_24px.xml
  Swimmer_seller/app/src/main/res/layout/activity_main.xml
  Swimmer_seller/app/src/main/res/layout/fragment_login.xml
  Swimmer_seller/app/src/main/res/layout/fragment_main.xml
  Swimmer_seller/app/src/main/res/layout/fragment_sign_up.xml
  Swimmer_seller/app/src/main/res/layout/fragment_sign_up_info.xml
  Swimmer_seller/app/src/main/res/navigation/nav_graph.xml
  Swimmer_seller/app/src/main/res/values-land/dimens.xml
  Swimmer_seller/app/src/main/res/values-w1240dp/dimens.xml
  Swimmer_seller/app/src/main/res/values-w600dp/dimens.xml
  Swimmer_seller/app/src/main/res/values/dimens.xml
  Swimmer_seller/app/src/main/res/values/strings.xml
  Swimmer_seller/build.gradle
Labels: feature, ui

#15 color, theme 추가 / functions 관련 빌드 파일 추가
  .firebaserc
  .gitignore
  .idea/FinalProject-ShoppingMallService-team3.iml
  .idea/modules.xml
  .idea/vcs.xml
  Swimmer_customer/app/src/main/res/values/colors.xml
  Swimmer_customer/app/src/main/res/values/themes.xml
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/UserRepository.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Seller.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/LoginFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/ResetPasswordFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/SignUpInfoFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/UserViewModel.kt
  Swimmer_seller/app/src/main/res/layout/fragment_reset_password.xml
  Swimmer_seller/app/src/main/res/navigation/nav_graph.xml
  Swimmer_seller/app/src/main/res/values/colors.xml
  Swimmer_seller/app/src/main/res/values/strings.xml
  Swimmer_seller/app/src/main/res/values/themes.xml
  firebase.json
  functions/.eslintrc.js
  functions/.gitignore
  functions/index.js
  functions/package-lock.json
  functions/package.json
Labels: setting

#14 [판매자용] 상품 등록
  .DS_Store
  Swimmer_seller/app/build.gradle
  Swimmer_seller/app/google-services.json
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/MainActivity.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Category.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Product.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Review.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/repository/ProductRepository.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/home/HomeFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/home/HomeViewModel.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/main/MainFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductAddFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductResult.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductViewModel.kt
  Swimmer_seller/app/src/main/res/drawable/add_photo_alternate_24px.xml
  Swimmer_seller/app/src/main/res/drawable/arrow_upward_24px.xml
  Swimmer_seller/app/src/main/res/drawable/headset_mic_24px.xml
  Swimmer_seller/app/src/main/res/drawable/home_24px.xml
  Swimmer_seller/app/src/main/res/drawable/local_shipping_24px.xml
  Swimmer_seller/app/src/main/res/drawable/menu_24px.xml
  Swimmer_seller/app/src/main/res/drawable/package_24px.xml
  Swimmer_seller/app/src/main/res/drawable/package_48px.xml
  Swimmer_seller/app/src/main/res/drawable/person_24px.xml
  Swimmer_seller/app/src/main/res/drawable/settings_24px.xml
  Swimmer_seller/app/src/main/res/drawable/shopping_bag_24px.xml
  Swimmer_seller/app/src/main/res/font/hsbombaram.ttf
  Swimmer_seller/app/src/main/res/layout/fragment_home.xml
  Swimmer_seller/app/src/main/res/layout/fragment_main.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_add.xml
  Swimmer_seller/app/src/main/res/menu/bottom_navigation_menu.xml
  Swimmer_seller/app/src/main/res/menu/drawer_navigation_menu.xml
  Swimmer_seller/app/src/main/res/navigation/fragment_nav_graph.xml
  Swimmer_seller/app/src/main/res/navigation/nav_graph.xml
  Swimmer_seller/app/src/main/res/values/strings.xml
  Swimmer_seller/app/src/main/res/values/themes.xml
Labels: feature, ui, question

#13 feat:사용자 로그인 ,회원가입, 이메일 찾기, 비밀번호 재설정
  Swimmer_customer/.idea/misc.xml
  Swimmer_customer/app/build.gradle
  Swimmer_customer/app/src/main/AndroidManifest.xml
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/model/User.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/repository/CustomerUserRepository.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/repository/UserRepository.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/HomeFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/findinfo/FindInfoFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/findinfo/FindInfoViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/login/LoginFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/login/LoginViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/main/MainActivity.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/main/MainFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/register/RegisterFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/register/RegisterViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/util/AutoLoginUtil.kt
  Swimmer_customer/app/src/main/res/drawable/done_24px.xml
  Swimmer_customer/app/src/main/res/drawable/kakaospare_24px.xml
  Swimmer_customer/app/src/main/res/font/font.xml
  Swimmer_customer/app/src/main/res/font/font_family.xml
  Swimmer_customer/app/src/main/res/font/hs.ttf
  Swimmer_customer/app/src/main/res/font/hsthin.ttf
  Swimmer_customer/app/src/main/res/layout/activity_main.xml
  Swimmer_customer/app/src/main/res/layout/fragment_find_info.xml
  Swimmer_customer/app/src/main/res/layout/fragment_home.xml
  Swimmer_customer/app/src/main/res/layout/fragment_login.xml
  Swimmer_customer/app/src/main/res/layout/fragment_main.xml
  Swimmer_customer/app/src/main/res/layout/fragment_register.xml
  Swimmer_customer/app/src/main/res/navigation/fragment_nav_graph.xml
  Swimmer_customer/app/src/main/res/navigation/nav_graph.xml
  Swimmer_customer/app/src/main/res/values/colors.xml
  Swimmer_customer/app/src/main/res/values/themes.xml
  Swimmer_customer/build.gradle
  Swimmer_seller/.idea/gradle.xml
  Swimmer_seller/.idea/misc.xml
Labels: feature, ui, question

#16 이메일 찾기, 비밀번호 재설정 기능 구현
  Swimmer_seller/app/build.gradle
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/repository/UserRepository.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/FindEmailFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/LoginFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/ResetPasswordFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/SignUpInfoFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/UserResult.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/UserViewModel.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/UserViewModelFactory.kt
  Swimmer_seller/app/src/main/res/layout/fragment_find_email.xml
  Swimmer_seller/app/src/main/res/layout/fragment_login.xml
  Swimmer_seller/app/src/main/res/navigation/nav_graph.xml
  Swimmer_seller/app/src/main/res/values/strings.xml
  functions/index.js
Labels: feature, fix

#19 [소비자용] 결제 화면 및 결제 완료 화면
  Swimmer_customer/app/build.gradle
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/model/Items.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/order/OrderCompleteFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/payment/CompleteFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/payment/PaymentFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/payment/repository/PaymentRepository.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/payment/vm/PaymentViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/ProductDetailFragment.kt
  Swimmer_customer/app/src/main/res/drawable/credit_score_24px.xml
  Swimmer_customer/app/src/main/res/drawable/defalut_dot.xml
  Swimmer_customer/app/src/main/res/drawable/dot_indicator.xml
  Swimmer_customer/app/src/main/res/drawable/gesture_select_24px.xml
  Swimmer_customer/app/src/main/res/drawable/selected_dot.xml
  Swimmer_customer/app/src/main/res/layout/fragment_complete.xml
  Swimmer_customer/app/src/main/res/layout/fragment_payment.xml
  Swimmer_customer/app/src/main/res/layout/payment_item_row.xml
  Swimmer_customer/app/src/main/res/navigation/fragment_nav_graph.xml
  Swimmer_customer/app/src/main/res/values/colors.xml
Labels: feature, ui

#17 Refactor : [소비자용] 상품 상세 viewBinding -> dataBinding
  Swimmer_customer/app/build.gradle
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/model/Ranking.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/HomeFragmentViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/ProductDetailFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/ProductViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/bindingAdapter/BindingAdapter.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/tablayout/ProductDetailTabFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/tablayout/ProductReviewTabFragment.kt
  Swimmer_customer/app/src/main/res/drawable/chip_state_color_list.xml
  Swimmer_customer/app/src/main/res/drawable/empty_star_rate.xml
  Swimmer_customer/app/src/main/res/drawable/expand_more_24px.xml
  Swimmer_customer/app/src/main/res/drawable/keyboard_arrow_down_24px.xml
  Swimmer_customer/app/src/main/res/drawable/star_rate.xml
  Swimmer_customer/app/src/main/res/drawable/star_rate_24px.xml
  Swimmer_customer/app/src/main/res/layout/fragment_home.xml
  Swimmer_customer/app/src/main/res/layout/fragment_main.xml
  Swimmer_customer/app/src/main/res/layout/fragment_order_complete.xml
  Swimmer_customer/app/src/main/res/layout/fragment_product_detail.xml
  Swimmer_customer/app/src/main/res/layout/fragment_product_detail_tab.xml
  Swimmer_customer/app/src/main/res/layout/fragment_product_review_tab.xml
  Swimmer_customer/app/src/main/res/layout/fragment_product_review_tab_chip_bottom_sheet.xml
  Swimmer_customer/app/src/main/res/layout/ranking_item.xml
  Swimmer_customer/app/src/main/res/values/colors.xml
  Swimmer_customer/app/src/main/res/values/strings.xml
  Swimmer_customer/hs_err_pid2336.log
  Swimmer_customer/hs_err_pid6988.log
  Swimmer_customer/hs_err_pid8316.log
  Swimmer_customer/hs_err_pid8724.log
Labels: refactor

#22 [판매자용] 메인화면 UI 구현, 상품 등록 해시태그 chip 기능 추가
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/MainActivity.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Product.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/home/HomeFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/main/MainFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductAddFragment.kt
  Swimmer_seller/app/src/main/res/layout/fragment_home.xml
  Swimmer_seller/app/src/main/res/layout/fragment_main.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_add.xml
  Swimmer_seller/app/src/main/res/layout/layout_chip_input.xml
  Swimmer_seller/app/src/main/res/values/strings.xml
Labels: feature, ui

#28 feat : [소비자용] 상품후기 화면 개발
  Swimmer_customer/app/build.gradle
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/model/Review.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/order/OrderFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/tablayout/ProductReviewTabFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/tablayout/ReviewAdapter.kt
  Swimmer_customer/app/src/main/res/drawable/custom_ratingbar.xml
  Swimmer_customer/app/src/main/res/drawable/custom_ratingbar_empty_star.xml
  Swimmer_customer/app/src/main/res/drawable/custom_ratingbar_star.xml
  Swimmer_customer/app/src/main/res/drawable/custom_review_item_image_view.xml
  Swimmer_customer/app/src/main/res/drawable/empty_star_rate_png.png
  Swimmer_customer/app/src/main/res/drawable/noimg.png
  Swimmer_customer/app/src/main/res/drawable/star_rate_png.png
  Swimmer_customer/app/src/main/res/layout/fragment_order.xml
  Swimmer_customer/app/src/main/res/layout/fragment_product_review_tab.xml
  Swimmer_customer/app/src/main/res/layout/fragment_product_review_tab_chip_bottom_sheet_height.xml
  Swimmer_customer/app/src/main/res/layout/fragment_product_review_tab_chip_bottom_sheet_size.xml
  Swimmer_customer/app/src/main/res/layout/fragment_product_review_tab_chip_bottom_sheet_star_rating.xml
  Swimmer_customer/app/src/main/res/layout/fragment_product_review_tab_chip_bottom_sheet_weight.xml
  Swimmer_customer/app/src/main/res/layout/fragment_product_review_tab_review_item.xml
  Swimmer_customer/app/src/main/res/layout/fragment_ranking_.xml
  Swimmer_customer/app/src/main/res/values/colors.xml
  Swimmer_customer/app/src/main/res/values/strings.xml
  Swimmer_customer/app/src/main/res/values/themes.xml
Labels: feature, ui

#26 [판매자용] 메뉴 화면 개발 & 마이페이지 화면 & 로그아웃 에러 해결
  Swimmer_seller/.idea/misc.xml
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/MainActivity.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/repository/UserRepository.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/main/MainFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/menu/MenuFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/mypage/MypageFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/UserViewModel.kt
  Swimmer_seller/app/src/main/res/drawable/add_24px.xml
  Swimmer_seller/app/src/main/res/drawable/navigate_next_24px.xml
  Swimmer_seller/app/src/main/res/layout/fragment_menu.xml
  Swimmer_seller/app/src/main/res/layout/fragment_mypage.xml
  Swimmer_seller/app/src/main/res/menu/navigation_rail_menu.xml
  Swimmer_seller/app/src/main/res/navigation/fragment_nav_graph.xml
  Swimmer_seller/app/src/main/res/values/strings.xml
Labels: ui

#32 [판매자용] 주문상태별 건 수 표시, 상품 이미지 첨부 기능
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Item.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Order.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Product.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/repository/OrderRepository.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/repository/ProductRepository.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/guide/GuideFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/home/HomeFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/home/HomeViewModel.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/main/MainFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductAddFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductOptionFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductResult.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductViewModel.kt
  Swimmer_seller/app/src/main/res/drawable/close_20px.xml
  Swimmer_seller/app/src/main/res/drawable/close_24px.xml
  Swimmer_seller/app/src/main/res/drawable/primary_with_opacity_background.xml
  Swimmer_seller/app/src/main/res/layout/fragment_guide.xml
  Swimmer_seller/app/src/main/res/layout/fragment_home.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_add.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_option.xml
  Swimmer_seller/app/src/main/res/layout/layout_imageview_delete.xml
  Swimmer_seller/app/src/main/res/navigation/fragment_nav_graph.xml
  Swimmer_seller/app/src/main/res/values/strings.xml
Labels: feature, fix

#36 [Feature] 주문목록
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Item.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Order.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Seller.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/repository/OrderRepository.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/main/MainFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/menu/MenuFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/order/OrderManageFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/order/OrderViewModel.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/order/OrderViewModelFactory.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/SignUpInfoFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/UserViewModel.kt
  Swimmer_seller/app/src/main/res/layout/fragment_home.xml
  Swimmer_seller/app/src/main/res/layout/fragment_menu.xml
  Swimmer_seller/app/src/main/res/layout/fragment_order_manage.xml
  Swimmer_seller/app/src/main/res/layout/row_order.xml
  Swimmer_seller/app/src/main/res/navigation/fragment_nav_graph.xml
  Swimmer_seller/app/src/main/res/values/strings.xml
Labels: feature, ui

#40 Feat : [소비자용]더미데이터에서 파이어베이스 데이터로 리팩토링, android veil 라이브러리 적용, 구매하기 버튼 Bottom Sheet Dialog 완성
  Swimmer_customer/.idea/deploymentTargetDropDown.xml
  Swimmer_customer/app/build.gradle
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/model/ItemsForCustomer.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/model/Product.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/model/ProductDetailModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/model/Ranking.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/model/exItemList.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/BannerViewPager2Adapter.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/HomeFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/HomeFragmentAdapter.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/main/MainFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/payment/PaymentFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/ProductDetailAdapter.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/ProductDetailFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/ProductViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/bindingAdapter/BindingAdapter.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/tablayout/ProductDetailTabFragment.kt
  Swimmer_customer/app/src/main/res/drawable/add_24px.xml
  Swimmer_customer/app/src/main/res/drawable/arrow_upward_24px.xml
  Swimmer_customer/app/src/main/res/drawable/custom_option_number_textview_box.xml
  Swimmer_customer/app/src/main/res/drawable/remove_24px.xml
  Swimmer_customer/app/src/main/res/layout/activity_product_detail_viewpage2.xml
  Swimmer_customer/app/src/main/res/layout/fragment_home.xml
  Swimmer_customer/app/src/main/res/layout/fragment_product_detail.xml
  Swimmer_customer/app/src/main/res/layout/fragment_product_detail_payment_button_bottom_sheet.xml
  Swimmer_customer/app/src/main/res/layout/fragment_product_detail_tab.xml
  Swimmer_customer/app/src/main/res/layout/item_profile.xml
  Swimmer_customer/app/src/main/res/values/colors.xml
  Swimmer_customer/app/src/main/res/values/strings.xml
Labels: feature, refactor

#43 주문 상세 화면 및 기능개발 & string 추출 & Order, Item Parcelable로 변경
  Swimmer_seller/app/build.gradle
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Item.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Order.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/OrderState.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Seller.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/repository/OrderRepository.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/repository/UserRepository.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/home/HomeFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/home/HomeViewModel.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/main/MainFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/order/OrderDetailFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/order/OrderManageFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/order/OrderViewModel.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/SignUpInfoFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/UserViewModel.kt
  Swimmer_seller/app/src/main/res/layout/fragment_order_detail.xml
  Swimmer_seller/app/src/main/res/layout/fragment_order_manage.xml
  Swimmer_seller/app/src/main/res/layout/row_order.xml
  Swimmer_seller/app/src/main/res/layout/row_order_item.xml
  Swimmer_seller/app/src/main/res/navigation/fragment_nav_graph.xml
  Swimmer_seller/app/src/main/res/values/strings.xml
Labels: feature, ui, refactor, setting

#45 [판매자용] 옵션 추가 화면 및 기능 구현, 메인화면 주문상태별 건수 표시, Safe Args 방식 데이터 전달, 데이터 클래스 Parcelable
  Swimmer_seller/app/build.gradle
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Category.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Item.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Product.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Review.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/home/HomeFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/home/HomeViewModel.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/home/HomeViewModelFactory.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductAddFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductOptionFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductViewModel.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductViewModelFactory.kt
  Swimmer_seller/app/src/main/res/drawable/check_24px.xml
  Swimmer_seller/app/src/main/res/drawable/seller_guide_image.jpg
  Swimmer_seller/app/src/main/res/layout/fragment_home.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_add.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_option.xml
  Swimmer_seller/app/src/main/res/layout/layout_bottom_sheet_option.xml
  Swimmer_seller/app/src/main/res/layout/layout_imageview_delete.xml
  Swimmer_seller/app/src/main/res/layout/row_product_option.xml
  Swimmer_seller/app/src/main/res/navigation/fragment_nav_graph.xml
  Swimmer_seller/app/src/main/res/values/strings.xml
  Swimmer_seller/build.gradle
Labels: feature, ui, fix

#50 splash 스크린, 개인정보 이용동의 & 회원정보 입력 유효성 검사
  Swimmer_seller/app/build.gradle
  Swimmer_seller/app/src/main/AndroidManifest.xml
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/MainActivity.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Seller.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/repository/UserRepository.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/SignUpInfoFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/user/UserViewModel.kt
  Swimmer_seller/app/src/main/res/layout/fragment_sign_up_info.xml
  Swimmer_seller/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Swimmer_seller/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Swimmer_seller/app/src/main/res/mipmap-hdpi/ic_launcher.png
  Swimmer_seller/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Swimmer_seller/app/src/main/res/mipmap-hdpi/ic_launcher_adaptive_back.png
  Swimmer_seller/app/src/main/res/mipmap-hdpi/ic_launcher_adaptive_fore.png
  Swimmer_seller/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  Swimmer_seller/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Swimmer_seller/app/src/main/res/mipmap-hdpi/ic_launcher_round_adaptive_back.png
  Swimmer_seller/app/src/main/res/mipmap-hdpi/ic_launcher_round_adaptive_fore.png
  Swimmer_seller/app/src/main/res/mipmap-mdpi/ic_launcher.png
  Swimmer_seller/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Swimmer_seller/app/src/main/res/mipmap-mdpi/ic_launcher_adaptive_back.png
  Swimmer_seller/app/src/main/res/mipmap-mdpi/ic_launcher_adaptive_fore.png
  Swimmer_seller/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  Swimmer_seller/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Swimmer_seller/app/src/main/res/mipmap-mdpi/ic_launcher_round_adaptive_back.png
  Swimmer_seller/app/src/main/res/mipmap-mdpi/ic_launcher_round_adaptive_fore.png
  Swimmer_seller/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  Swimmer_seller/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Swimmer_seller/app/src/main/res/mipmap-xhdpi/ic_launcher_adaptive_back.png
  Swimmer_seller/app/src/main/res/mipmap-xhdpi/ic_launcher_adaptive_fore.png
  Swimmer_seller/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  Swimmer_seller/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Swimmer_seller/app/src/main/res/mipmap-xhdpi/ic_launcher_round_adaptive_back.png
  Swimmer_seller/app/src/main/res/mipmap-xhdpi/ic_launcher_round_adaptive_fore.png
  Swimmer_seller/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  Swimmer_seller/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Swimmer_seller/app/src/main/res/mipmap-xxhdpi/ic_launcher_adaptive_back.png
  Swimmer_seller/app/src/main/res/mipmap-xxhdpi/ic_launcher_adaptive_fore.png
  Swimmer_seller/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  Swimmer_seller/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Swimmer_seller/app/src/main/res/mipmap-xxhdpi/ic_launcher_round_adaptive_back.png
  Swimmer_seller/app/src/main/res/mipmap-xxhdpi/ic_launcher_round_adaptive_fore.png
  Swimmer_seller/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  Swimmer_seller/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Swimmer_seller/app/src/main/res/mipmap-xxxhdpi/ic_launcher_adaptive_back.png
  Swimmer_seller/app/src/main/res/mipmap-xxxhdpi/ic_launcher_adaptive_fore.png
  Swimmer_seller/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  Swimmer_seller/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Swimmer_seller/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round_adaptive_back.png
  Swimmer_seller/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round_adaptive_fore.png
  Swimmer_seller/app/src/main/res/values/strings.xml
  Swimmer_seller/app/src/main/res/values/themes.xml
Labels: feature, ui

#48 Feat : HomeFragment viewPager2 자동 스크롤 + 애니메이션 추가
  Swimmer_customer/app/build.gradle
  Swimmer_customer/app/src/main/AndroidManifest.xml
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/model/Product.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/model/Ranking.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/model/exItemList.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/BannerViewPager2Adapter.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/HomeFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/HomeFragmentAdapter.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/main/MainActivity.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/ProductDetailFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/ProductViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/bindingAdapter/BindingAdapter.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/tablayout/ProductDetailTabFragment.kt
  Swimmer_customer/app/src/main/res/drawable/splash.gif
  Swimmer_customer/app/src/main/res/layout/fragment_home.xml
  Swimmer_customer/app/src/main/res/layout/fragment_product_detail.xml
  Swimmer_customer/app/src/main/res/layout/fragment_product_review_tab_review_item.xml
  Swimmer_customer/app/src/main/res/layout/ranking_item.xml
  Swimmer_customer/app/src/main/res/raw/favorite.json
  Swimmer_customer/app/src/main/res/values/colors.xml
  Swimmer_customer/app/src/main/res/values/strings.xml
  Swimmer_customer/app/src/main/res/values/themes.xml
Labels: feature, refactor

#53 Refactor : homeFragment ViewPager2 로딩 속도 개선
  Swimmer_customer/.idea/deploymentTargetDropDown.xml
  Swimmer_customer/app/build.gradle
  Swimmer_customer/app/src/main/AndroidManifest.xml
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/model/Product.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/HomeFragmentViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/home/BannerViewPager2Adapter.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/home/HomeFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/home/HomeFragmentAdapter.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/home/HomeFragmentViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/home/repository/HomeRepository.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/ProductDetailFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/ProductViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/bindingAdapter/BindingAdapter.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/tablayout/ProductDetailTabFragment.kt
  Swimmer_customer/app/src/main/res/layout/fragment_home.xml
  Swimmer_customer/app/src/main/res/layout/fragment_product_detail_tab.xml
  Swimmer_customer/app/src/main/res/navigation/fragment_nav_graph.xml
  Swimmer_customer/app/src/main/res/values-land/dimens.xml
  Swimmer_customer/app/src/main/res/values-v23/themes.xml
  Swimmer_customer/app/src/main/res/values-w1240dp/dimens.xml
  Swimmer_customer/app/src/main/res/values-w600dp/dimens.xml
  Swimmer_customer/app/src/main/res/values/dimens.xml
  Swimmer_customer/app/src/main/res/values/strings.xml
Labels: refactor

#58 Feat : [판매자용] 상품 목록, 상품 필터링 & 정렬, 상품 상세, 리뷰 목록
  Swimmer_customer/.idea/misc.xml
  Swimmer_customer/build.gradle
  Swimmer_seller/app/build.gradle
  Swimmer_seller/app/src/main/AndroidManifest.xml
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Product.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Review.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/repository/ProductRepository.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/home/HomeFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/main/MainFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/order/OrderViewModel.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductAddFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductDetailFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductDetailTabLayoutAdapter.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductListFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductOptionFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductViewModel.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/tab/ProductDetailTabFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/tab/ProductQnaTabFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/tab/ProductReviewTabFragment.kt
  Swimmer_seller/app/src/main/res/drawable/edit_24px.xml
  Swimmer_seller/app/src/main/res/drawable/expand_more_20px.xml
  Swimmer_seller/app/src/main/res/drawable/ios_share_24px.xml
  Swimmer_seller/app/src/main/res/drawable/loading_placeholder.png
  Swimmer_seller/app/src/main/res/drawable/share_24px.xml
  Swimmer_seller/app/src/main/res/drawable/star_24px.xml
  Swimmer_seller/app/src/main/res/drawable/tag_20px.xml
  Swimmer_seller/app/src/main/res/drawable/tune_20px.xml
  Swimmer_seller/app/src/main/res/layout/fragment_home.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_detail.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_detail_tab.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_list.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_option.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_option_bottom_sheet.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_qna_tab.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_review_tab.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_review_tab_bottom_sheet_height.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_review_tab_bottom_sheet_size.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_review_tab_bottom_sheet_star.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_review_tab_bottom_sheet_weight.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_review_tab_item.xml
  Swimmer_seller/app/src/main/res/layout/item_chip.xml
  Swimmer_seller/app/src/main/res/layout/item_chip_input.xml
  Swimmer_seller/app/src/main/res/layout/item_image_slider.xml
  Swimmer_seller/app/src/main/res/layout/item_imageview_delete.xml
  Swimmer_seller/app/src/main/res/layout/item_product_list.xml
  Swimmer_seller/app/src/main/res/layout/item_product_option.xml
  Swimmer_seller/app/src/main/res/layout/row_product.xml
  Swimmer_seller/app/src/main/res/navigation/fragment_nav_graph.xml
  Swimmer_seller/app/src/main/res/values/strings.xml
  Swimmer_seller/build.gradle
Labels: feature, ui, fix

#65 Feat : [판매자용] 상품 옵션 색상, 사이즈 고정 기준으로 정렬
  Swimmer_customer/.idea/deploymentTargetDropDown.xml
  Swimmer_customer/.idea/misc.xml
  Swimmer_seller/.idea/deploymentTargetDropDown.xml
  Swimmer_seller/.idea/misc.xml
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductOptionFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductViewModel.kt
  Swimmer_seller/app/src/main/res/layout/fragment_product_option_bottom_sheet.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_review_tab_item.xml
Labels: feature

#68 refactor: 마이페이지 ui다듬기
  Swimmer_customer/app/src/main/res/layout/fragment_mypage.xml
Labels: ui, refactor

#69 refactor: 로그인 문구 추가
  Swimmer_seller/app/src/main/res/layout/fragment_login.xml
Labels: ui, refactor

#72 [판매자용] 상품 후기 목록 기반 평점 계산, 평점 분포 반영
  Swimmer_customer/.idea/misc.xml
  Swimmer_seller/.idea/deploymentTargetDropDown.xml
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/tab/ProductReviewTabFragment.kt
  Swimmer_seller/app/src/main/res/layout/fragment_product_review_tab.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_review_tab_bottom_sheet_weight.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_review_tab_item.xml
Labels: feature, ui

#77 [사용자용]프로필사진, 닉네임 표시, ui 수정,개인정보 수정 ui 일부
  Swimmer_customer/.idea/deploymentTargetDropDown.xml
  Swimmer_customer/app/build.gradle
  Swimmer_customer/app/src/main/AndroidManifest.xml
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/repository/CustomerUserRepository.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/deliverypointmanage/AddressDialogFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/deliverypointmanage/DeliveryPointManageFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/login/LoginFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/login/LoginViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/main/MainFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/modifyinfo/CheckPasswordFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/modifyinfo/CheckPasswordViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/mypage/MypageFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/mypage/MypageViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/payment/PaymentFragment.kt
  Swimmer_customer/app/src/main/res/drawable/broken_image_24px.xml
  Swimmer_customer/app/src/main/res/layout/copy.xml
  Swimmer_customer/app/src/main/res/layout/fragment_address_dialog.xml
  Swimmer_customer/app/src/main/res/layout/fragment_check_password.xml
  Swimmer_customer/app/src/main/res/layout/fragment_delivery_point_manage.xml
  Swimmer_customer/app/src/main/res/layout/fragment_detail_address.xml
  Swimmer_customer/app/src/main/res/layout/fragment_modify_info.xml
  Swimmer_customer/app/src/main/res/layout/fragment_mypage.xml
  Swimmer_customer/app/src/main/res/layout/item_delivery_point.xml
  Swimmer_customer/app/src/main/res/navigation/fragment_nav_graph.xml
  Swimmer_customer/app/src/main/res/values/strings.xml
  Swimmer_customer/build.gradle
Labels: feature, ui

#79 refactor: 주문목록 -> 주문상세 객체 전달
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/OrderDetailFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/model/ItemsForCustomer.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/model/Order.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/order/OrderListFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/order/OrderViewModel.kt
  Swimmer_customer/app/src/main/res/navigation/fragment_nav_graph.xml
Labels: refactor, fix

#82 fix: 주문상세 진입 에러 해결
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/model/Order.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/data/repository/OrderRepository.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/order/OrderDetailFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/order/OrderManageFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/order/OrderViewModel.kt
  Swimmer_seller/app/src/main/res/layout/fragment_order_detail.xml
  Swimmer_seller/app/src/main/res/navigation/fragment_nav_graph.xml
Labels: fix

#83 feat: 주문상세 기능 구현
  Swimmer_customer/.idea/misc.xml
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/OrderDetailFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/mypage/MypageFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/order/OrderDetailFragment.kt
  Swimmer_customer/app/src/main/res/layout/fragment_order_detail.xml
  Swimmer_customer/app/src/main/res/layout/row_order_detail.xml
  Swimmer_customer/app/src/main/res/navigation/fragment_nav_graph.xml
  Swimmer_customer/build.gradle
Labels: feature

#80 [소비자용] 주문 화면 정보처리 & order 객체 데이터 전송 & 데이터 에러 처리
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/model/ItemsForCustomer.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/model/Order.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/repository/OrderRepository.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/payment/PaymentFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/payment/repository/PaymentRepository.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/payment/vm/PaymentViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/ProductDetailFragment.kt
  Swimmer_customer/app/src/main/res/layout/fragment_payment.xml
Labels: feature, refactor, fix

#86 [판매자용] 판매자 가이드, 화면 전환 애니메이션, String 분리
  Swimmer_customer/.idea/deploymentTargetDropDown.xml
  Swimmer_seller/.idea/deploymentTargetDropDown.xml
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/guide/GuideFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductAddFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductDetailFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductListFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductOptionFragment.kt
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/tab/ProductReviewTabFragment.kt
  Swimmer_seller/app/src/main/res/anim/slide_in_left.xml
  Swimmer_seller/app/src/main/res/anim/slide_in_right.xml
  Swimmer_seller/app/src/main/res/anim/slide_out_left.xml
  Swimmer_seller/app/src/main/res/anim/slide_out_right.xml
  Swimmer_seller/app/src/main/res/drawable/guid_add_option1.png
  Swimmer_seller/app/src/main/res/drawable/guide_add_option2.png
  Swimmer_seller/app/src/main/res/drawable/guide_add_product.jpg
  Swimmer_seller/app/src/main/res/drawable/guide_product_detail.png
  Swimmer_seller/app/src/main/res/drawable/guide_product_list.png
  Swimmer_seller/app/src/main/res/drawable/package_2_48px.xml
  Swimmer_seller/app/src/main/res/layout/fragment_guide.xml
  Swimmer_seller/app/src/main/res/layout/fragment_home.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_add.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_detail.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_detail_tab.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_list.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_option.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_option_bottom_sheet.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_qna_tab.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_review_tab.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_review_tab_bottom_sheet_height.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_review_tab_bottom_sheet_size.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_review_tab_bottom_sheet_star.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_review_tab_bottom_sheet_weight.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_review_tab_item.xml
  Swimmer_seller/app/src/main/res/navigation/fragment_nav_graph.xml
  Swimmer_seller/app/src/main/res/navigation/nav_graph.xml
  Swimmer_seller/app/src/main/res/values/strings.xml
Labels: ui, refactor

#67 docs : README.md 작성
  README.md
  Swimmer_customer/.idea/deploymentTargetDropDown.xml
  Swimmer_customer/.idea/misc.xml
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/CategoryFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/FavoriteFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/HistoryFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/model/Order.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/repository/OrderRepository.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/home/BannerViewPager2Adapter.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/home/HomeFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/home/HomeFragmentAdapter.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/home/HomeFragmentViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/order/OrderListFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/payment/vm/PaymentViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/ProductDetailAdapter.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/ProductDetailFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/bindingAdapter/BindingAdapter.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/tablayout/ProductQnATabFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/tablayout/ProductReviewTabFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/tablayout/ReviewAdapter.kt
  Swimmer_customer/app/src/main/res/layout/fragment_category.xml
  Swimmer_customer/app/src/main/res/layout/fragment_favorite.xml
  Swimmer_customer/app/src/main/res/layout/fragment_history.xml
  Swimmer_customer/app/src/main/res/layout/fragment_order_detail.xml
  Swimmer_customer/app/src/main/res/layout/fragment_product_qn_a_tab.xml
  Swimmer_customer/app/src/main/res/raw/developing.json
  Swimmer_customer/app/src/main/res/values/strings.xml
  Swimmer_seller/.idea/misc.xml
  image-1.png
  image-2.png
  image-3.png
  image.png
  img.png
  img_1.png
  img_10.png
  img_11.png
  img_12.png
  img_13.png
  img_14.png
  img_15.png
  img_16.png
  img_17.png
  img_18.png
  img_19.png
  img_2.png
  img_20.png
  img_21.png
  img_22.png
  img_23.png
  img_24.png
  img_25.png
  img_26.png
  img_27.png
  img_3.png
  img_4.png
  img_5.png
  img_6.png
  img_7.png
  img_8.png
  img_9.png
Labels: bug, documentation, feature, ui

#84 [사용자용]개인정보 수정 / 회원탈퇴
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/model/User.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/repository/CustomerUserRepository.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/login/LoginFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/login/LoginViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/modifyinfo/ModifyInfoFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/modifyinfo/ModifyInfoViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/mypage/MypageFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/register/RegisterFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/register/RegisterViewModel.kt
  Swimmer_customer/app/src/main/res/layout/fragment_modify_info.xml
  Swimmer_customer/app/src/main/res/layout/fragment_mypage.xml
  Swimmer_customer/app/src/main/res/layout/fragment_order_detail.xml
  Swimmer_customer/app/src/main/res/layout/fragment_register.xml
  Swimmer_customer/app/src/main/res/navigation/fragment_nav_graph.xml
  Swimmer_customer/app/src/main/res/values/strings.xml
  Swimmer_customer/build.gradle
Labels: feature, ui, question

#92 [사용자용]화면전환 애니메이션 일부 수정, 백버튼 동작 적용, 사용자용 판매자용 로그인 분기처리, 백버튼종료-> 자동로그인 버그수정
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/repository/CustomerUserRepository.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/data/repository/UserRepository.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/deliverypointmanage/AddressDialogFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/deliverypointmanage/DeliveryPointManageFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/detailAddress/DetailAddressFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/findinfo/FindInfoFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/home/HomeFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/login/LoginFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/modifyinfo/CheckPasswordFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/modifyinfo/ModifyInfoFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/mypage/MypageFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/payment/CompleteFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/payment/PaymentFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/payment/vm/PaymentViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/product/ProductDetailFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/register/RegisterFragment.kt
  Swimmer_customer/app/src/main/res/navigation/fragment_nav_graph.xml
Labels: feature, fix

#93 [사용자용] 백버튼 제어 마무리, 주석 추가, 일부 뷰 코드 최적화
  Swimmer_customer/.idea/misc.xml
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/deliverypointmanage/AddressDialogFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/deliverypointmanage/DeliveryPointManageFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/detailAddress/DetailAddressFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/modifyinfo/CheckPasswordFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/modifyinfo/ModifyInfoFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/modifyinfo/ModifyInfoViewModel.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/mypage/MypageFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/register/RegisterFragment.kt
  Swimmer_customer/app/src/main/res/values/strings.xml
Labels: feature, refactor

#96 [사용자용]주문 목록, 주문 상세 애니메이션,백버튼
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/order/OrderDetailFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/order/OrderListFragment.kt
  Swimmer_customer/app/src/main/res/navigation/fragment_nav_graph.xml
Labels: feature, ui

#99 94 minor fix
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/deliverypointmanage/DeliveryPointManageFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/payment/CompleteFragment.kt
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/payment/PaymentFragment.kt
  Swimmer_customer/app/src/main/res/layout/fragment_address_dialog.xml
  Swimmer_customer/app/src/main/res/layout/fragment_check_password.xml
  Swimmer_customer/app/src/main/res/layout/fragment_complete.xml
  Swimmer_customer/app/src/main/res/layout/fragment_delivery_point_manage.xml
  Swimmer_customer/app/src/main/res/layout/fragment_detail_address.xml
  Swimmer_customer/app/src/main/res/layout/fragment_modify_info.xml
  Swimmer_customer/app/src/main/res/layout/fragment_mypage.xml
  Swimmer_customer/app/src/main/res/layout/fragment_payment.xml
  Swimmer_customer/app/src/main/res/layout/item_delivery_point.xml
  Swimmer_customer/app/src/main/res/navigation/fragment_nav_graph.xml
Labels: ui, refactor, fix

#103 fix : 판매자앱 애니메이션 효과 롤백
  Swimmer_seller/.idea/deploymentTargetDropDown.xml
  Swimmer_seller/app/src/main/res/animator/nav_default_enter_anim.xml
  Swimmer_seller/app/src/main/res/animator/nav_default_exit_anim.xml
  Swimmer_seller/app/src/main/res/animator/nav_default_pop_enter_anim.xml
  Swimmer_seller/app/src/main/res/animator/nav_default_pop_exit_anim.xml
Labels: fix

#112 fix: #111 클릭가능 범위 확대
  Swimmer_customer/app/src/main/res/layout/fragment_mypage.xml
Labels: bug, ui

#115 fix: 상품 상세페이지 상품 대표 이미지 길이 늘이기(비율 개선)
  Swimmer_customer/app/src/main/res/layout/fragment_product_detail.xml
Labels: ui, refactor

#117 Fix : [판매자용] 상품 등록 이미지 툴팁 추가, 태그 helper text 잘리는 오류 수정
  Swimmer_seller/.idea/deploymentTargetDropDown.xml
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/ProductAddFragment.kt
  Swimmer_seller/app/src/main/res/drawable/help_20px.xml
  Swimmer_seller/app/src/main/res/layout/fragment_product_add.xml
  Swimmer_seller/app/src/main/res/values/strings.xml
Labels: fix

#119 [사용자용] 네비게이션 바 수정 ,배송지 관리 -> 마이페이지 애니메이션 수정
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/main/MainFragment.kt
  Swimmer_customer/app/src/main/res/navigation/fragment_nav_graph.xml
Labels: ui, fix

#122 개발자 정보/버전 표기
  Swimmer_customer/.idea/deploymentTargetDropDown.xml
  Swimmer_customer/app/src/main/AndroidManifest.xml
  Swimmer_customer/app/src/main/java/com/petpal/swimmer_customer/ui/login/LoginFragment.kt
  Swimmer_customer/app/src/main/res/layout/fragment_login.xml
  Swimmer_customer/app/src/main/res/values/strings.xml
  Swimmer_seller/app/src/main/res/layout/fragment_login.xml
  Swimmer_seller/app/src/main/res/values/strings.xml
  Swimmer_seller/build.gradle
Labels: ui

#123 Fix : 판매자용 글자 크기 확대시 텍스트 잘림 해결
  Swimmer_seller/app/src/main/java/com/petpal/swimmer_seller/ui/product/tab/ProductReviewTabFragment.kt
  Swimmer_seller/app/src/main/res/layout/fragment_product_review_tab.xml
  Swimmer_seller/app/src/main/res/layout/item_product_list.xml
Labels: fix
